1- Preprocessing fichier Metagames(score des jeux vidéos/ source : metacritic)

In [322]:
#importation de la bibliothèque "pandas"
import pandas as pd

In [323]:
#transformation et lecture du fichier "metagames" dans un dataframe
metagames = pd.read_csv("metagames.csv")

#affichage des 5 premières lignes 
metagames.head(5)

#visualisation des informations du dataframe 
metagames.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19519 entries, 0 to 19518
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   19519 non-null  int64
 1   Name         19519 non-null  object
 2   Year         19519 non-null  object
 3   Platform     19519 non-null  object
 4   Meta_scores  19519 non-null  int64
 5   User_scores  19519 non-null  object
 6   year         19519 non-null  int64
dtypes: int64(3), object(4)
memory usage: 1.0+ MB

I - Focus sur la Variable "Name":

In [324]:
#Instanciation d'un dictionnaire, d1

d1 = {' ' : '-',
     ':': "", 
     "'" : "",
    '---': "-", 
    '--':  "-"}

# Définition d'une fonction qui remplace les valeurs d'une colonne d'un dictionnaire 
def replace_values(mydict,mycol,mydf):                                                                                       
    mydf.replace({mycol: mydict}, regex=True, inplace = True)
    return mydf

#Définition d'une fonction qui convertit tous les caractères majuscules d'une chaîne en caractères minuscules et la renvoie.
def lower_col(mycol, mydf):
    mydf [mycol] = mydf[mycol].str.lower()
    return mydf


#Définition d'une fonction qui supprime une colonne du dataframe 
def delete_col (col, mydf): 
    mydf.drop(col,axis = 1, inplace = True)
    return mydf

In [325]:
#Instanciation des arguments liés aux trois fonctions : 

mycol = "Name"
mydf = metagames
col = "Unnamed: 0"


lower_col(mycol, mydf)
replace_values(d,mycol,mydf)
delete_col (col, mydf)

,Name,Year,Platform,Meta_scores,User_scores,year
0,the-legend-of-zelda-ocarina-of-time,1998-11-23,Nintendo 64,99,9.1,1998
1,tony-hawks-pro-skater-2,2000-09-20,PlayStation,98,7.4,2000
2,grand-theft-auto-iv,2008-04-29,PlayStation 3,98,7.8,2008
3,soulcalibur,1999-09-08,Dreamcast,98,8.4,1999
4,grand-theft-auto-iv,2008-04-29,Xbox 360,98,7.9,2008
...,...,...,...,...,...,...
19514,vroom-in-the-night-sky,2017-04-05,Switch,17,3.2,2017
19515,leisure-suit-larry-box-office-bust,2009-05-05,PlayStation 3,17,1.9,2009
19516,yaris,2007-10-10,Xbox 360,17,4.4,2007
19517,ride-to-hell-retribution,2013-06-24,PC,16,1.4,2013
19518,family-party-30-great-games-obstacle-arcade,2012-12-04,Wii U,11,2.5,2012

II- Focus sur la variable plateforme :

In [326]:
#instanciation de l'argument mycol par la variable 'Platform' du dataframe 
mycol = "Platform"

# instanciation du dataframe 
mydf = metagames

#création du dictionnaire, nommé d2 
d2= {' ': '-'}

#instanciation de mydict = d2
mydict = d2

#fonction lower
lower_col(mycol, mydf)

#fonction replace_values
replace_values(mydict,mycol,mydf)

,Name,Year,Platform,Meta_scores,User_scores,year
0,the-legend-of-zelda-ocarina-of-time,1998-11-23,nintendo-64,99,9.1,1998
1,tony-hawks-pro-skater-2,2000-09-20,playstation,98,7.4,2000
2,grand-theft-auto-iv,2008-04-29,playstation-3,98,7.8,2008
3,soulcalibur,1999-09-08,dreamcast,98,8.4,1999
4,grand-theft-auto-iv,2008-04-29,xbox-360,98,7.9,2008
...,...,...,...,...,...,...
19514,vroom-in-the-night-sky,2017-04-05,switch,17,3.2,2017
19515,leisure-suit-larry-box-office-bust,2009-05-05,playstation-3,17,1.9,2009
19516,yaris,2007-10-10,xbox-360,17,4.4,2007
19517,ride-to-hell-retribution,2013-06-24,pc,16,1.4,2013
19518,family-party-30-great-games-obstacle-arcade,2012-12-04,wii-u,11,2.5,2012

In [327]:
#instanciation de l'argument col2 
col2 = ["Meta_scores", "User_scores","Year", "year"]

#definition d'une fonction qui supprime les variables de col 2
def delete_col(col, mydf): 
  
    mydf.drop(col,axis = 1, inplace = True)
    return mydf

In [328]:
# creation d'un dataframe : composé de deux variables 'name', 'platform'

delete_col(col2 ,metagames)

                                              Name       Platform
0              the-legend-of-zelda-ocarina-of-time    nintendo-64
1                          tony-hawks-pro-skater-2    playstation
2                              grand-theft-auto-iv  playstation-3
3                                      soulcalibur      dreamcast
4                              grand-theft-auto-iv       xbox-360
...                                            ...            ...
19514                       vroom-in-the-night-sky         switch
19515           leisure-suit-larry-box-office-bust  playstation-3
19516                                        yaris       xbox-360
19517                     ride-to-hell-retribution             pc
19518  family-party-30-great-games-obstacle-arcade          wii-u

[19519 rows x 2 columns]

III- Webscraping (commentaires des gameurs : source metacritic)

In [332]:
#importation librairie re 
import re
#import
import csv
#importation beautifulsoup , request 
import requests, bs4
#importation de la fonction get de la librairie request
from requests import get
#importation beautifulsoup 
from bs4 import BeautifulSoup
#importation clear_output depuis la librairie Ipython.core.display
from IPython.core.display import clear_output
#importation warnings 
from warnings import warn
#importation de la librairie sleep , time 
from time import sleep
# importation de radint 
from random import randint
#importation de la fonction time depuis la librairie 
from time import time

/var/folders/_9/vh0_w1913cl55z4dr30h2vbc0000gn/T/ipykernel_32476/1406771405.py:12: DeprecationWarning: Importing clear_output from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import clear_output

In [331]:
#Création d'en-tête HTTP qui permet d'envoyer des requêtes au serveur et qu'elles soient acceptées

headers = {
    'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko)Chrome/70.0.3538.77 Safari/537.36'}

In [ ]:
#Paramétrage du monitoring 
start_time = time()
#Instanciation de la requête à 0 
requests = 0

filepath=''

lines=0
for i in metagames:
    
#Creation d'une liste g, permettant de stocker les informations scrappées 
    g=[]
    #création d'une url qui prend les variables (Name, Platforme) du dataframe metagames
    game = get('https://www.metacritic.com/game/'+i,headers = headers)
    #initialisation de la requête et du temps de l'execution du monitoring 
    requests += 1
    elapsed_time = time() - start_time
    print('Request:{}; Frequency: {} requests/s'.format(requests, requests/elapsed_time))
    clear_output(wait = True)
    
    # Affichage si le status code qui est de 20000000 est retourné 
    if game.status_code != 2000000:
        warn('Request: {}; Status code: {}'.format(requests,game.status_code))   
        #si la requête est superieure à 2000000 cassez la boucle 
    if requests > 2000000:
        warn('Number of requests was greater than expected.')
        break
    
    #instanciation de BeautifulSoup  
    game_soup = BeautifulSoup(game.text, 'html.parser')
    
    #Rechercher la balise majeure user_review 
    right_class = game_soup.find_all('li', class_="user_review")
    
    #création d'une liste user_data pour stocker les données scrappées
    user_data = []
    
    # condition que la balise est trouvé:
    if right_class:
        
        # itération des items dans la balise majeur  
        for item in right_class:
            # Scrapping de la note du commentaire 
            if item.find('div', class_="metascore_w"):
                s= item.find('div', class_="metascore_w").text
            else: s=''
                
             # Scrapping du commentaire 
            if item.find("span", class_="blurb"):
                reviews =item.find("span", class_="blurb")
                
            else: reviews =item.find("div", class_="review_body") 
            #stockage du commentaire en format texte 
            r= reviews.text
            
            #stockage des commentaires et des notes dans une liste 
            user_data=[i,s,r] 
            g.append(user_data)
            #lignes suivantes 
            lines=lines+1
    
        #création du dataframe df
        df = pd.DataFrame(g)
        
        #ouverture et stockage des données dans un fichier csv 
        with open(filepath+'user_review1b.csv', 'a') as f:
            df.to_csv(f, index=False, quoting=csv.QUOTE_NONNUMERIC, sep="|")
        #vide le contenu de la liste pour l'itération suivante 
        g=[]

In [ ]:
#Lecture du fichier csv , user review en dataframe
metagames_new = pd.read_csv('critic_review1.csv', sep='|', header=None)

 IV- Webscraping (commentaires des critics : source metacritic)

In [ ]:
#Paramétrage du monitoring 
start_time = time()
#instanciation de la requête à 0 
requests = 0

filepath=''

lines=0
for i in metagames:
    
#Creation d'une liste g, permettant de stocker les informations scrappées 
    g=[]
    #création d'une url qui prend les variables (Name, Platforme) du dataframe metagames
    game = get('https://www.metacritic.com/game/'+i,headers = headers)
    #initialisation de la requête et du temps de l'execution du monitoring 
    requests += 1
    elapsed_time = time() - start_time
    print('Request:{}; Frequency: {} requests/s'.format(requests, requests/elapsed_time))
    clear_output(wait = True)
    
    # Affichage si le status code qui est de 20000000 est retourné 
    if game.status_code != 2000000:
        warn('Request: {}; Status code: {}'.format(requests,game.status_code))   
        #si la requête est superieure à 2000000 cassez la boucle 
    if requests > 2000000:
        warn('Number of requests was greater than expected.')
        break
    
    #instanciation de BeautifulSoup  
    game_soup = BeautifulSoup(game.text, 'html.parser')
    
    #Rechercher la balise majeure user_review 
    right_class = game_soup.find_all('li', class_="critic_review")
    
    #création d'une liste user_data pour stocker les données scrappées
    user_data = []
    
    # condition si la balise est trouvé:
    if right_class:
        
        # itération des items dans la balise majeur  
        for item in right_class:
            # Scrapping de la note du commentaire 
            if item.find('div', class_="review_grade"):
                s= item.find('div', class_="review_grade").text
            else: s=''
                
             # Scrapping du commentaire 
            if item.find("span", class_="blurb"):
                reviews =item.find("span", class_="blurb")
            else: reviews =item.find("div", class_="review_body")
                
            #stockage du commentaire en format texte 
            r= reviews.text
            
            #stockage des commentaires et des notes dans une liste 
            user_data=[i,s,r] 
            g.append(user_data)
            #lignes suivantes 
            lines=lines+1
    
        #création du dataframe df
        df = pd.DataFrame(g)
        
        #ouverture et stockage des données dans un fichier csv 
        with open(filepath+'critic_review.csv', 'a') as f:
            df.to_csv(f, index=False, quoting=csv.QUOTE_NONNUMERIC, sep="|")
        #vide le contenu de la liste pour l'itération suivante 
        g=[]